### ISSUE TITLE
Add `tabular` to hara.test

### ISSUE THREAD

**Issue by WhittlesJr** [hoebat/hara#4]
Midje's `tabular` macro is very important for me. 

But while I'm asking about this, what are the real advantages of `hara.test` over `midje`? Is it just that the implementation is simpler? Or is there a concrete advantage for the user? I'm having a hard time figuring that out.

**Comment by WhittlesJr** [comment]
I also can't live without `(autotest)` from midje.

**Comment by zcaudate** [comment]
I was a real advocate of `midje` and used it for a long time. I implemented a version similar to `hara.test` for clojurescript using the karma test runner. I've since deleted the original repo, but a copy of it can be found here: https://github.com/yayitswei/purnam. 

- I wanted to understand the internals of what was happening. I also wanted to customise how my tests looked (it's much easier when it's my own code). And yes, `hara.test` is a much simpler implementation because it does strip a lot of things out that I don't use.

- I've built a documentation generation framework around the tests (which for me is really useful as the tests and docstrings are generated from test files). Again, I've deleted the public repo but there are older videos that show the workflow.
- docstrings - https://www.youtube.com/watch?v=Kis8Pmg2pBA
- publishing docs - https://www.youtube.com/watch?v=8FjvhDPIUWE

- `tabular` is a little bit tricky to add in but if it is added, I'd like it changed so that `tabular` goes inside the `fact` form .

**Comment by zcaudate** [comment]
Regarding autotest, I've found that it breaks quite a bit (because it uses the tools.namespace workflow) and it's actually easier if everything is in repl.

**Comment by zcaudate** [comment]
For tabular: https://github.com/marick/Midje/wiki/Tabular-facts

I'd think switching on the `:type` key would be a pretty good design. 

Something like this:

    ^{:type :table}
    (fact "This is a rip off of midje's tabular"

      (active? <cell-status> <neighbor-count>) 
      => <expected>
  
      [<cell-status>  <neighbor-count>  <expected>]
      | :alive         1                 FALSEY        ; underpopulation
      | :alive         2                 truthy       
      | :alive         3                 truthy
      | :alive         4                 FALSEY        ; overpopulation
 
      ;; A newborn cell has three parents
      | :dead          2                 FALSEY
      | :dead          3                 truthy
      | :dead          4                 FALSEY)

@WhittlesJr - I'm a little busy at the moment but if you'd like to have a go at it, a PR would be most welcome.

**Comment by zcaudate** [comment]
The square bracket and the `|` makes it a little easier to parse and to check for errors.

**Comment by WhittlesJr** [comment]
I have to say, I definitely like your syntax proposal better. But I think for now I'm going to stick with Midje proper for testing, since it's working for my purposes at the moment.

**Comment by zcaudate** [comment]
ah sweet. I'll close this for now.
